{% set name = "tox-conda" %}
{% set version = "0.9.0" %}
{% set sha256 = "306ad28d93d22bfd33ef2af5ee916cb15e6748ec1a5b9930d5aa4d2fbd5f12f4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tox_conda-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools_scm
  run:
    - python >=3.5
    - tox >=3.8.1,<4

test:
  imports:
    - tox_conda.plugin

about:
  home: https://github.com/tox-dev/tox-conda
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: tox plugin that provides integration with conda
  doc_url: https://github.com/tox-dev/tox-conda
  dev_url: https://github.com/tox-dev/tox-conda

extra:
  recipe-maintainers:
    - njzjz
    - ickc
