{% set name = "tox-conda" %}
{% set version = "0.10.2" %}
{% set sha256 = "7011ca43c3f46791e74ba217405e1cba433e7bcc77d26ef3b019340ef020c5e8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tox_conda-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - tox >=3.8.1,<4
    - ruamel.yaml >=0.15.0,<0.18

test:
  requires:
    - python {{ python_min }}
  imports:
    - tox_conda.plugin

about:
  home: https://github.com/tox-dev/tox-conda
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: tox plugin that provides integration with conda
  doc_url: https://github.com/tox-dev/tox-conda
  dev_url: https://github.com/tox-dev/tox-conda

extra:
  recipe-maintainers:
    - njzjz
    - ickc
