{% set name = "tox-conda" %}
{% set version = "0.10.1" %}
{% set sha256 = "83a3ee0271409ec2b23ad502d057db5cf0ea1bf4028f0bc56d65540351634495" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tox_conda-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools_scm
  run:
    - python >=3.5
    - tox >=3.8.1,<4
    - ruamel.yaml >=0.15.0,<0.18

test:
  imports:
    - tox_conda.plugin

about:
  home: https://github.com/tox-dev/tox-conda
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: tox plugin that provides integration with conda
  doc_url: https://github.com/tox-dev/tox-conda
  dev_url: https://github.com/tox-dev/tox-conda

extra:
  recipe-maintainers:
    - njzjz
    - ickc
